services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/node_modules
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
    depends_on:
      - postgres
    networks:
      - laravel
    ports:
      - "9000:9000"
      - "5173:5173"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

volumes:
  db_data:
  storage:
  cache:
  node_modules:

networks:
  laravel:
